// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "../src/BridgeEntry.sol";
import "../src/LatentBridgeVerifier.sol";

contract BridgeTest is Test {
    BridgeEntry public bridgeEntry;
    Halo2Verifier public verifier;

    function setUp() public {
        verifier = new Halo2Verifier();
        bridgeEntry = new BridgeEntry(address(verifier));
    }

    function test_zk_proof_verification() public {
        // Read the raw binary calldata generated by ezkl encode-evm-calldata
        // Paths are relative to the project root where forge is executed
        string memory path = string.concat(vm.projectRoot(), "/../calldata.json");
        bytes memory payload = vm.readFileBinary(path);

        // The payload is ABI-encoded for `verifyProof(bytes,uint256[])`
        // We will modify the 4-byte function selector to match `BridgeEntry.processBridge(bytes,uint256[])`
        bytes4 newSelector = BridgeEntry.processBridge.selector;
        payload[0] = newSelector[0];
        payload[1] = newSelector[1];
        payload[2] = newSelector[2];
        payload[3] = newSelector[3];

        // Call BridgeEntry with the modified payload
        (bool success, ) = address(bridgeEntry).call(payload);
        
        // Assert that the transaction was successful (meaning the ZK proof was valid)
        assertTrue(success, "BridgeEntry processBridge failed");
    }
}
